# Generated by Django 2.0.6 on 2021-10-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='computo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
