# Generated by Django 2.0.6 on 2021-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_tabla_computo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='computo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
